<a href="https://colab.research.google.com/github/SHUBHAM6247/AIML/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
insert numpy as np

SyntaxError: invalid syntax (<ipython-input-1-38bc34f5ae8d>, line 1)

In [2]:
import numpy as np


In [3]:
 a = np.array([1,2,3])
 b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
 c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],dtype = float)

In [4]:
a

array([1, 2, 3])

In [5]:
b


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [6]:
1 d = np.array([5,6,7])

SyntaxError: invalid syntax (<ipython-input-6-36defa1b8ba5>, line 1)

In [7]:
d = np.array([5,6,7])

In [8]:
e=a+d

In [9]:
e

array([ 6,  8, 10])

In [10]:
f = np.array([(3.5,4,8),(7,8,9)],dtype = float)

In [11]:
f

array([[3.5, 4. , 8. ],
       [7. , 8. , 9. ]])

In [12]:
g=b+f

In [13]:
g

array([[ 5.,  6., 11.],
       [11., 13., 15.]])

In [14]:
b = f = np.array([(7,3,1),(14,15,29)], dtype = float)

In [15]:
f

array([[ 7.,  3.,  1.],
       [14., 15., 29.]])

In [16]:
f.sort()

In [17]:
f

array([[ 1.,  3.,  7.],
       [14., 15., 29.]])